### ISSUE TITLE
questions on nova_get_nvmm_pfn?

### ISSUE THREAD

**Issue by clachan** [Andiry/nova#2]
Hi Andriy,

I have two questions here:

1) in dax.c:699, both nvmm_addr and mmap_addr were on NVM, should we use memcpy_to_pmem_nocache instead of memcpy here?
2) Is this mmap_addr the 'replica' page you mentioned in the paper section 4.5?

Thanks,
Clay

**Comment by Andiry** [comment]
Hi Clay,

2) Yes.

1) Because they are replica pages, we do not need to persist them here - they will disappear if a power failure occurs, and applications may write to these pages later. Only when msync() occurs, we will commit these pages and persist them.
