### ISSUE TITLE
address_space_operations.direct_IO not used?

### ISSUE THREAD

**Issue by lynus** [Andiry/nova#3]
Hello, Andiry. I'm reading your code. Really great work!
It seems like nova_aops_dax.directed_IO() is not used both in nova_dax_file_read() and nova_dax_file_write()
and NOVA so far has not handled O_DIRECT flag.
Maybe O_DIRECT is obsolete in memory file system with dax feature.

**Comment by Andiry** [comment]
Hi Lingyu,

direct_IO is called from upper layer, when application specifies
O_DIRECT flag. So O_DIRECT is handled in NOVA implicitly.

Thanks,
Andiry
